const awards = [
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Site of the day",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Agency of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Best site of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
    {
        name: "Independent of the year",
        type: "Nominee",
        project: "INNOVATE 2024",
        label: "Awwwards",
    },
];